apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: k8s-lb
  namespace: tutorial
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "hands-on-ip"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: app1-service
          servicePort: 8081
